### ISSUE TITLE
Support OAuth2 Authentication as provided in REST 2.x API

### ISSUE THREAD

**Issue by jaymzmac** [Pure-Storage-Ansible/FlashArray-Collection#245]
My understanding is that the current implementation only supports API tokens for authentication to the FlashArray. 

It would be good to have the option of authenticating using the more secure OAuth2 method that is provided in REST 2.x API (and supported in the py-pure-client sdk):

```
from pypureclient import flasharray
client = flasharray.Client('flasharray.example.com',
                           private_key_file=[...],
                           private_key_password=[...],
                           username=[...],
                           client_id=[...],
                           key_id=[...],
                           issuer=[...])
```

**Comment by sdodsley** [comment]
This is planned, but with a large number of arrays out there that still only support REST 1.x this will have to wait until all Purity versions that cannot support OAuth2 are EOL.

**Comment by jaymzmac** [comment]
Can you expand a little on why it's not possible to offer OAuth2 as an option for those users with Purity versions that support it? Just trying to understand why it has to be either/or, rather than supporting both.

**Comment by sdodsley** [comment]
We could, but what happens when you try to manage a fleet of arrays with different Purity versions and different authentication methods. You would have to supply parameters for both authentication methods for every task. This makes the playbook and any associated roles more complex.
TBH no one has actually asked for OAuth2 in the Ansible modules to date and so that feature is well down our priority list.
