### ISSUE TITLE
support for certificates >3000 characters

### ISSUE THREAD

**Issue by mhueske** [Pure-Storage-Ansible/FlashArray-Collection#545]
purefa_certs supports only up to 3000 characters for certificate files while importing.
We generate certificates with a 4096 bit key on our CA and therefore the length of the generated certificate exceeds 3000 characters.
This module does not allow to import those certificates while the FlashArray WebUI accepts and imports exactly the same certificates without having any issues.
So please check if there is any option to change this behaviour.
Thanks.

**Comment by sdodsley** [comment]
Unfortunatlry this limit is imposed by the Python SDK and beyond that the API endpoint for certificates in Purity. This has been raised with our internal FlashArray engineering teams.
When they produce a fix we will roll this into the Asible Collection.
It might be worth raising this with you Pure Storage account team so that they are aware of the 3000 character limit and can add weight to engineering to resolve this.

**Comment by mhueske** [comment]
Thank you for your feedback and the explaination. I will get in contact with the account team as suggested.

**Comment by sdodsley** [comment]
@mhueske i have solved this issue. There will be a patch to fix this shortly.

**Comment by mhueske** [comment]
Great, thanks. I can confirm the issue is resolved with this commit :+1:
