### ISSUE TITLE
Unable to remove suffix

### ISSUE THREAD

**Issue by darthVikes** [Pure-Storage-Ansible/FlashArray-Collection#688]
**Describe the bug**

Looking at the purefa_snap documentation, the only variable that is required is name.

So the below code without "suffix" will give you:  "state is copy but all the following are missing: suffix"

  purefa_snap:
    name: "{{ item.value.source }}"
    target: "{{ item.value.target }}"
    overwrite: true
    fa_url: "{{ source_pure }}"
    api_token: "{{ api_token }}"
    state: copy

The below config will give you ""Suffix name does not conform to suffix name rules"}"

  purefa_snap:
    name: "{{ item.value.source }}"
    suffix: ""
    target: "{{ item.value.target }}"
    overwrite: true
    fa_url: "{{ source_pure }}"
    api_token: "{{ api_token }}"
    state: copy

**To Reproduce**

see above code example

**Expected behavior**
Removing "suffix" would work without causing an error.

Current version I am using:
purestorage               1.19.0
py-pure-client            1.47.0

ansible [core 2.14.17]
  config file = /opt/repo/orca/ansible.cfg
  configured module search path = ['/opt/repo/orca/library']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /opt/repo/orca/collections
  executable location = /usr/bin/ansible
  python version = 3.9.19 (main, Sep 11 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

**Comment by sdodsley** [comment]
@darthVikes Unfortunately, due to the way Ansible documentation is constructed we can only list `required` for parameters that are needed for EVERY state option. In this case `suffix` is required for the `copy` state, together with `target`. Some other states do not require a `suffix`, such as `present` as this will create a suffix based on the timestamp - as in the Pureity//FA GUI.
As this is a snapshot you must have a suffix.
I think where this is going wrong is that you are passing `name: "{{ item.value.source }}"` which is (IU assume) the full snapshot name, which consists of `name` and `suffix`. 
You will need to split `"{{ item.value.source }}"` into its component parts and pass each to the appropriate parameter.

**Comment by darthVikes** [comment]
Gotcha, that makes sense.   Wonder if it's possible to put in a note in there somewhere about that?  

Anyway, I think part of my issue was wanting to copy a volume vs copying a snapshot?  Had it confused a bit.   The snapshot when you create one, you have to enter a suffix, which it then adds the suffix to the snapshot name.    So went and created a snapshot of the other volumes I needed.   So my bad as snapshot it requires a suffix anyway when you create one.   I'll go ahead and close.
